### PR TITLE
Release

### PR DESCRIPTION
**Pull request by NaguiHW**

### CODE REVIEW

**Comment by JamesOkunlade** [comment]
## TSE working on it

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Hello, dev!! ✋ 😄 Nice work on your Tic-Tac-Toe project 👏 Here are some things you'll have to improve on.

- Using an alert box to announce a winner is not a good practice, display a message block above the gameboard instead.
- There is no option for restart when the game ends in a draw.
- Should be able to take players' names.
- Very importantly, this project follows the lesson about Factory Functions and The Module Pattern so the main goal is to put into practice those concepts along with the main concepts of Object-Oriented Programming. Particularly, classes/objects and how to access their methods and attributes. Divide your script into different modules say play, gameboard, and Game.
- When you're done with point 3, ensure not to have mixed dom-manipulation tasks with the game logic.

**Please fix those points and request for a re-review.** 

**Status: `Changes required`**

Happy coding! 😎

**Review by AdnanAfsari — CHANGES_REQUESTED** [review]
Hello @NaguiHW @bernardogarza ✋ 

Nice work guys but you need little bit of work, you are yet to implement one point the previous reviewer requested.

- [ ] Very importantly, this project follows the lesson about Factory Functions and The Module Pattern so the main goal is to put into practice those concepts along with the main concepts of Object-Oriented Programming. Particularly, classes/objects and how to access their methods and attributes. Divide your script into different modules say play, gameboard, and Game.

When you're done with point 3, ensure not to have mixed dom-manipulation tasks with the game logic.
Please fix those points and request for a re-review.

**Status: Changes required**

Happy Coding

**Review by AdnanAfsari — APPROVED** [review]
Hello @bernardogarza ✋ 

Looks good.Its a 👍 from me.

Status: Approved

Happy coding

Adnan Afsari

**Pull request merged**
